name: Dependency Review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    uses: basel5001/githubinfra/.github/workflows/dependency-review.yml@main